export type SeoConfig = {
  title: string;
  description: string;
  keywords: string[];
  logo: string;
};

export const seoConfig: SeoConfig = {
  title: 'Team Maverick India',
  description: 'Official website of Team Maverick India - Wolves of the Sky!',
  keywords: [
    'aviation',
    'aerospace',
    'team maverick',
    'india',
    'engineering',
    'aircraft',
    'drones',
    'innovation',
    'pccoe',
    'pimpri chinchwad college of engineering',
    'pimpri',
    'chinchwad',
    'akurdi',
    'nigdi',
    'college',
    'aviation excellence',
    'flight technology',
    'piloting',
    'aircraft safety',
    'aeronautical engineering',
    'modern aviation',
    'aircraft design',
    'aviation research',
    'drone technology',
    'unmanned aerial vehicles',
    'aviation competitions',
    'aircraft maintenance',
    'aviation community',
    'aerospace innovation',
    'flight simulation',
    'air traffic control',
    'pilot career',
    'aviation enthusiasts',
    'aircraft performance',
    'team',
    'rc aircraft',
    'radio controlled',
    'uavs',
    'Dassault systemes',
    'Ansys',
    'Altium',
    'Solidworks',
    'APC Props',
    'Mathworks',
    'Trade Syndicate',
    'T-motors',
    'HiTech',
    'Simscale',
    'Onyx Technology',
    'Tattu UAV',
    'Gens',
    'Dubro',
    'XPS',
    'E-calc',
    'Elite',
    'Art Aads',
    'Cad n Cart',
    '3D Wizard',
    'Packsquare',
    'Chetan Enterprises',
    'Horizon Engineers',
    'Mitter Fasteners',
    'Shreeyash Enterprises',
    'Grape Embassy',
    'Society of Automotive Engineers',
    'SAE Aero Design West',
    'Aerodesign',
    'Aerodynamics',
    'Drone Development Challenge',
    'DDC',
    'SAEISS',
    'Student Team',
    'Team Maverick India',
    'PCCOE',
    'Team Maverick PCCOE',
    'Drones',
    'Unmanned Aerial Vehicles',
    'Autonomous Aircrafts',
    'SAE International',
    'All India Rank 1',
    'National Champions',
    'Pune',
    'SAE India',
    'Aerial Aerobatics',
    'Innovation',
    'Research and Development',
    'Design',
    'Manufacturing',
    'Avionics',
    'Structures',
    'Fabrication',
    'Maverick',
    'Top Gun Maverick',
    'Wolves of the sky',
    'BLDC Motor',
    'testing',
    'fixed-wing',
    'SAE',
    'SAEINDIA Western Section',
    'SAEINDIA Southern Section',
    'SAEINDIA Eastern Section',
    'SAEINDIA Northern Section',
    'highest payload',
    'wingspan',
    'Multi Operational Heavy Aerial Vehicle',
    'MOHAV',
    'USA',
    'California',
    'Van Nyus',
    'Las Vegas',
    'Los Angeles',
    'San Fransisco',
    'Texas',
    'Fuselage',
    'Monokote',
    'stand out',
    'shortest takeoff distance',
    'established in 2021',
    
    
  ],
  logo: '/images/logo.png'
};